### ISSUE TITLE
When batch_size > 1, Rater flow is aggregating wrong groups for majority vote and average score.

### ISSUE THREAD

**Issue by CambioML** [CambioML/uniflow#118]
Credit to @Panzy-18 to find this issue through his experiment.

As stated in https://github.com/CambioML/uniflow/pull/109#issuecomment-1888021544. When batch_size > 1, Rater flow is aggregating wrong groups for majority vote and average score.

**Comment by goldmermaid** [comment]
Issue is fixed in https://github.com/CambioML/uniflow/pull/128.
